export const projectData=[
    {
        id:"lorestore",
        img:"https://github.com/dhirajksharma/thelorestore-frontend/blob/main/public/android-chrome-512x512.png?raw=true",
        cover:"https://github.com/dhirajksharma/thelorestore-frontend/blob/main/src/res/thumb.jpg?raw=true",
        tag:["MongoDB", "Express.JS", "React.JS", "TailwindCSS"],
        link:"https://thelorestore.vercel.app/",
        title:"The Lore Store",
        intro:"Introducing Lore Store, an engaging online book store where readers can explore an extensive collection of literary treasures. With a user-friendly interface, seamless navigation, and secure transactions via Stripe, Lore Store offers an immersive browsing experience. Embark on a journey through captivating narratives and discover your next literary adventure at Lore Store today.",
        insp:"During my B.Tech program, I was given the opportunity to work on a project related to software engineering. This project aimed to apply the theoretical knowledge we gained from studying various product development cycles into a practical setting. For my assignment, I was tasked with creating an online book store using a frontend framework of my choice and implementing a NoSQL backend system.",
        jrny:[
            "It was a semester-long project that began with the identification of a target user base, conducting surveys, and collecting data from potential users. One of the key lessons I learned during this project was the importance of asking the right questions to the appropriate audience. While gathering users' personal input was crucial, it needed to be verified with data before implementation.",
            "After identifying the user base and their product requirements, we created a Software Requirements Specification (SRS) and developed a project plan that included scheduling all stages of development and setting deadlines. Data flow diagrams were then constructed to provide a clear overview of the various processes involved before commencing the development phase.",
            "Initially, taking on a project of this scale as my first backend project felt daunting. However, by following the outlined steps and adhering to the established process, the development process became more streamlined. I approached the project by building one component at a time and gradually integrating them into the system. Whenever I encountered challenges, I referred to MongoDB documentation to find optimized solutions. Since the backend and frontend were deployed on separate servers, I faced hurdles in implementing Cross-Origin Resource Sharing (CORS). It took some time to overcome these obstacles, but once I understood how it worked, things became easier.",
            "Once a significant portion of the backend was completed, I shifted my focus to frontend development. I chose React to build the frontend and utilized Redux for state management and data sharing between components. To design the user interface, I sought inspiration from platforms like Dribbble, opting for a minimalistic and straightforward approach. I must admit that compared to backend development, frontend work required significantly more time and effort. The frontend development phase took me more than twice as long as the backend phase.",
            "Overall, the development process alone took approximately one and a half months. Some features proved more challenging to implement than others, and certain aspects had to be adjusted due to deadline constraints. Nevertheless, I was able to bring the project close to its initial plan. Upon deploying the finished work, I realized the complexities involved in integrating the frontend and backend seamlessly. Managing states during fetch requests and handling communication failures between the two servers were critical considerations. Neglecting these aspects could result in a system failure. This experience further deepened my appreciation for the tremendous effort developers put into running and maintaining massive platforms like Amazon and Flipkart.",
        ],
        chal:"Curabitur rhoncus posuere turpis, eget dignissim urna interdum vitae. Donec malesuada, nisl ac tincidunt mollis, mauris erat gravida erat, quis commodo magna nisi eget nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut sit amet odio et tortor dictum elementum at sed risus. Vivamus eget dui commodo, fermentum quam vitae, elementum eros. Vivamus eget nisi dictum, scelerisque purus eget, dictum orci. Quisque fringilla aliquet ligula, eget eleifend leo ullamcorper ut. Nulla scelerisque consequat suscipit. Curabitur mattis leo erat. Praesent sed tortor ultrices orci vulputate faucibus. Fusce laoreet purus non sem euismod, vel ornare augue accumsan. Phasellus quis finibus diam."
    },
    {
        id:"psreact",
        img:"https://github.com/dhirajksharma/reactgames/blob/main/src/res/logo.png?raw=true",
        cover:"https://github.com/dhirajksharma/reactgames/blob/main/public/react-games.jpg?raw=true",
        tag:["React.JS","TailwindCSS"],
        link:"https://psreact.vercel.app",
        title:"PS React",
        intro:"Welcome to PS React, a platform built for casual gaming enthusiasts. Dive into a world of entertainment with classic games like Hangman and Lights Out, designed to challenge and delight. Experience fun, sharpen your skills, with fellow gamers at PS React today.",
        insp:"When I was learning vanilla JS, I created a Pokemon game. Therefore, it seemed logical for me to develop more games when I began working with React JS. Considering the multitude of task schedulers already available on Github, it didn't make sense to add yet another one to the collection. You see, there's a certain enthusiasm and excitement that comes with working on an original idea, which is lacking when you're recreating an already existing project.",
        jrny:[
            "When I first started learning React, one of the first significant assignments I received was to create a game called Hangman. At first, I wasn't quite sure what kind of game it was. upon some googling I discovered that Hangman is like a precursor to Wordle—a game where you try to guess the 5 letters of a random word within 6 attempts.  It seemed like a nice and easy task.",
            "However, the main purpose of this assignment was to learn React and its functionalities. Therefore, the game was supposed to be designed using a group of components, each with its own role. These components would come together to form the entire game, interacting with each other through states and props, and passing data among themselves. As for the words, I utilized an API that would provide a random word every time it was played.",
            "After completing Hangman, I worked on another game called Lights Out. In this game, the player is presented with a grid of lit and unlit cells, and the objective is to turn off all the lit cells. As I worked on this second assignment, an idea sparked in my head—I should combine all these games into a single application. Drawing on the concepts I had learned so far, such as component lifecycles, routing mechanisms, and events in React, I began building this collection of games, all written in React- thus the name, PS React.",
            "When I initially deployed the application, the user interface did not have an appeal to it and was not up to my satisfaction. Every time I opened the site, it bothered me. Almost a year later, I had an epiphany—I should adopt a Tinder-like cards layout. Swipe left, swipe right—simple and intuitive. However, I soon realized that this approach would not be ideal if a user wanted to revisit a game card after going through all five games. The Tinder-style approach wouldn't allow for that. So, I decided to implement a carousel of cards instead. Equipped with a better understanding of UI layouts, font pairing, color combinations, and the use of Tailwind CSS, I completely revamped the site to its current state.",
            "In the end, when I finally deployed the new version of the site, I felt a sense of accomplishment and pride in how far I had come. I could literally see the progress I had made. This, I believe, is a crucial aspect of being a developer or any artist in general—you learn, practice, and continually improve. It's an iterative process where you constantly refine your work."
        ],
        chal:"Curabitur rhoncus posuere turpis, eget dignissim urna interdum vitae. Donec malesuada, nisl ac tincidunt mollis, mauris erat gravida erat, quis commodo magna nisi eget nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut sit amet odio et tortor dictum elementum at sed risus. Vivamus eget dui commodo, fermentum quam vitae, elementum eros. Vivamus eget nisi dictum, scelerisque purus eget, dictum orci. Quisque fringilla aliquet ligula, eget eleifend leo ullamcorper ut. Nulla scelerisque consequat suscipit. Curabitur mattis leo erat. Praesent sed tortor ultrices orci vulputate faucibus. Fusce laoreet purus non sem euismod, vel ornare augue accumsan. Phasellus quis finibus diam."
    },
    {
        id:"pokeduel",
        img:"https://github.com/dhirajksharma/pokeduel/blob/main/res/pokeball.png?raw=true",
        cover:"https://github.com/dhirajksharma/pokeduel/blob/main/res/pokeduel.png?raw=true",
        tag:["JavaScript", "jQuery"],
        link:"https://dhirajksharma.github.io/pokeduel/",
        title:"Poké Duel",
        intro:"Prepare yourselves for the PokéDuel! Choose your favorite Pokémon, challenge a friend, and engage them in battles. Emerge victorious by outsmarting your opponent and proving your Pokémon mastery at PokéDuel today.",
        insp:"This is a rather simple project I created while I was still learning DOM Manipulation. It began with a basic grid of Pokémon, but it swiftly evolved (pun intended) into something far beyond a simple half-hour assignment. I believe it all stems from my childhood love for Pokémon and the nostalgic feelings that this assignment triggered in me. It simply didn't feel satisfying enough to have so many cool Pokémon displayed on my screen without being able to interact with them in any way.",
        jrny:[
            "I quickly began brainstorming ideas, knowing the game couldn't be overly complex, but I always strive to push my limits. After generating some rough concepts for the game and considering the interface, it was time to gather some Pokémon! Fortunately, the community had generously created multiple resources for this purpose. However, I encountered my first hurdle: all these resources provided APIs to access their data, and I had no knowledge about APIs.",
            "But then I discovered that they had documented how to use their APIs and the various available endpoints. This meant I only needed to learn how APIs work and how to incorporate them into my game. That's when I came across async-await and Axios, which turned out to be beautiful tools. The joy I felt when encountering my first obstacle and solving it on my own, by reading documentation and articles from fellow developers, made me feel like a developer myself!",
            "I never realized how amazing APIs could be. I found one or two for everything I needed, from Pokémon data to their types and attacks. In fact, the official Pokémon website itself provides some incredible APIs for the community to use free of charge. With my designs and data prepared, I began writing the code, which involved a lot of JavaScript, nested functions, and numerous query selectors. It was quite a task. However, that was when I stumbled upon jQuery, a small but fast JavaScript library that greatly simplified this process, especially when it came to incorporating animations.",
            "It took me some time, but eventually I reached a point where I was satisfied with the game and shared it with my friends—a two-player Pokémon game of my own creation! Each Pokémon had random attributes, unique attacks, and strength bars, all battling against each other. To add the finishing touches, I included some music and a dark mode switch for those who preferred a cozy playing environment."
        ],
        chal:"Curabitur rhoncus posuere turpis, eget dignissim urna interdum vitae. Donec malesuada, nisl ac tincidunt mollis, mauris erat gravida erat, quis commodo magna nisi eget nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut sit amet odio et tortor dictum elementum at sed risus. Vivamus eget dui commodo, fermentum quam vitae, elementum eros. Vivamus eget nisi dictum, scelerisque purus eget, dictum orci. Quisque fringilla aliquet ligula, eget eleifend leo ullamcorper ut. Nulla scelerisque consequat suscipit. Curabitur mattis leo erat. Praesent sed tortor ultrices orci vulputate faucibus. Fusce laoreet purus non sem euismod, vel ornare augue accumsan. Phasellus quis finibus diam."
    }
]

export const experienceData=[
    {
        year:"2020-2024",
        title:"B. Tech in Computer Science",
        location:"Techno Main Salt Lake",
        details:"During my undergrad, I acquired a diverse range of skills. From programming languages and algorithms to collaboration and teamwork, I developed a strong technical foundation. Courses in relational databases, operating systems, and networking expanded my knowledge, while frontend development taught me web technologies and UI/UX principles. Additionally, I cultivated critical thinking, problem-solving, and time management abilities. This comprehensive skill set has prepared me to tackle real-world challenges with confidence and creativity as I enter the next phase of my career."
    },
]